blueprints/list.py
from flask import Blueprint,g,render_template,request,redirect,flash,url_for
from .forms import TodoForm
from models import ToDoModel
from exts import db

bp=Blueprint("list",__name__,url_prefix='/list')

@bp.route("/home")
def home():
    # 将登陆的用户名称获取并显示在导航栏中
    context = {
        "user": g.user.username
    }
    return render_template("list_home.html",**context)

@bp.route("/detail")
def detail():
    context = {
        "user": g.user.username
    }
    return render_template("list_detail.html",**context)

@bp.route("/add",methods=['GET','POST'])
def add():
    if request.method == 'GET':
        context = {
            "user": g.user.username
        }
        return render_template("list_add.html", **context)
    else:
        context = {
            "user": g.user.username
        }
        form = TodoForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            category = form.category.data
            todo = ToDoModel(title=title,content=content,category=category,user=g.user)
            db.session.add(todo)
            db.session.commit()
            return redirect(url_for('list.home'))
        else:
            print("something wrong")
            print(form.errors)
            flash("Invalid format!")
            return redirect(url_for('list.add'))


@bp.route("/finished")
def finished():
    context = {
        "user": g.user.username
    }
    return render_template("list_finished.html",**context)

@bp.route("/unfinished")
def unfinished():
    context = {
        "user": g.user.username
    }
    return render_template("list_unfinished.html",**context)

blueprints/user.py
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash
from .forms import RegistForm,LoginForm
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify,session,g
from exts import mail,db
from flask_mail import Message
from models import EmailCodeModel,UserModel
import string
import random
bp = Blueprint("user", __name__, url_prefix='/')


@bp.route("/",methods=['GET','POST'])
def login():
    if request.method == 'GET':
        print("the method is get")
        return render_template("user_login.html")
    else:
        # get the form from the html
        form= LoginForm(request.form)
        if form.validate():
            username=form.username.data
            password=form.password.data
            # if user exist and password is right, then jump to the list page
            # otherwise, show the error message
            user = UserModel.query.filter_by(username=username).first()
            if user and check_password_hash(user.password,password):
                print(user)
                session['user_id']=user.id
                return redirect(url_for("list.home"))
            else:
                flash("Invalid username or password! Please check again!")
                return redirect(url_for("user.login"))
        else:
            flash("Invalid format! Please check again!")
            return redirect(url_for("user.login"))


@bp.route("/registration",methods=['GET','POST'])
def regist():
    if request.method == 'GET':
        return render_template("user_regist.html")
    else:
        # get registration form from html
        form = RegistForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            # use hash code to ensure password security
            hash_password = generate_password_hash(password)
            user = UserModel(email=email, username=username, password=hash_password)
            # registrate successfully, commit user information to databse
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            # print("email: "+form.email.data)
            # print("username: "+form.username.data)
            # print("password: "+form.password.data)
            # print("password_confirm "+form.password_confirm.data)
            # print(form.validate())
            flash("Invalid registration format! Username length:1-20, password length:6,20!")
            return redirect(url_for("list.home"))


@bp.route("/mail", methods=['POST'])
def get_verification():
    # get email from form in html
    email = request.form.get("email")
    # set random verified codes
    letters = string.ascii_letters + string.digits
    verified_code = "".join(random.sample(letters, 4))
    if email:
        # send verified message to the email
        message = Message(
            subject="Verification Code from To do list",
            recipients=[email],
            body=f"You code is: {verified_code}. Please do not tell anyone else."
        )
        mail.send(message)

        # query whether this email had a verified code already
        # if it has, then update to the newest code
        # otherwise, create a new email&verified code in database
        catch_model = EmailCodeModel.query.filter_by(email=email).first()
        if catch_model:
            catch_model.catch = verified_code
            catch_model.create_time = datetime.now()
            db.session.commit()
        else:
            catch_model = EmailCodeModel(email=email, catch=verified_code)
            db.session.add(catch_model)
            db.session.commit()
        # code: 200->successfully update the verifying information
        return jsonify({"code": 200})
    else:
        # code:400->client service error
        return jsonify({"code": 400, "message": "Sending email successfully!"})

templates/list_add.html
{% extends "list_base.html" %}
{% block title %}Add{% endblock %}

{% block head %}


<script src="{{ url_for('static',filename="assets/jquery.min.js") }}"></script>
<script src="{{ url_for('static',filename="assets/moment.min.js")}}"></script>
  <script src="{{ url_for('static',filename="assets/bootstrap.min.js")}}"></script>
<script src="{{ url_for('static',filename="assets/bootstrap-datetimepicker.min.js")}}"></script>
<script src="{{ url_for('static',filename="JS/add.js")}}"></script>
      <link rel="stylesheet" href="{{ url_for('static',filename="bootstrap/bootstrap.4.6.min.css") }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='css/user.css') }}">
{% endblock %}

{% block body %}
{#<div class="container">#}
{#  <div class="row">#}
{#    <div class="col">#}
{#      <h2>Step1 Heading</h2>#}
{#    </div>#}
{#    <div class="col">#}
{#      <h2>Step2 Content</h2>#}
{#    </div>#}
{#  </div>#}
{#  <br>#}
{#  <div class="row">#}
{#    <div class="col">#}
{#      <h2>Step3 Category</h2>#}
{#    </div>#}
{#    <div class="col">#}
{#      <h2>Step4 DDL</h2>#}
{#    </div>#}
{#  </div>#}
{#</div>#}

  <div class="container">
  <div class="row">
    <div class="col-5">Steps 滚动监听</div>
    <div class="col-7" >
      <form id="add" action="{{ url_for('list.add')}}" method="post">
{#      单行输入框#}
      <div class="form-group">
        <input  type="text" name="title" class="form-control" placeholder="Enter the title">
      </div>
{#      多行输入框#}
      <div class="form-group">
        <textarea   name="content" class="form-control" rows="10" placeholder="Enter the content"></textarea>
      </div>

      <div class="form-group">
        <input  type="text" name="category" class="form-control" placeholder="Enter category here">
      </div>

{#      <div class="form-group">#}
{#        <label class="col-sm-2 control-label">Deadline</label>#}
{#         <div class="col-sm-10">#}
{#           <input type="text" class="form-control" id="ddl" placeholder="Deadline">#}
{#         </div>#}
{#      </div>#}

      <div class="form-group">
        {% for message in get_flashed_messages() %}
          <div class="form-group">
            <div class="text-danger">{{ message }}</div>
          </div>
        {% endfor %}
      </div>


      <div class="form-group">
        <button class="btn btn-primary btn-lg btn-block">Submitting</button>
      </div>
    </form>
    </div>
  </div>
  </div>
{% endblock %}

templates/list_base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
{#<script src="{{ url_for('static',filename="assets/jquery.min.js") }}"></script>#}
{#<script src="{{ url_for('static',filename="assets/moment.min.js")}}"></script>#}
{#<script src="{{ url_for('static',filename="assets/bootstrap.min.js")}}"></script>#}
{#<script src="{{ url_for('static',filename="assets/bootstrap-datetimepicker.min.js")}}"></script>#}
{##}
{#<link rel="stylesheet" href="{{ url_for('static',filename="assets/bootstrap.min.css")}}">#}
{#<link rel="stylesheet" href="{{ url_for('static',filename="assets/bootstrap-datetimepicker.min.css")}}">#}


  <link rel="stylesheet" href="{{ url_for('static',filename="bootstrap/bootstrap.4.6.min.css") }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='css/user.css') }}">
  {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{ url_for('list.home') }}">{{ user }}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-link" href="{{ url_for('list.add') }}">Add</a>
      <a class="nav-link" href="{{ url_for('list.finished') }}">Finished</a>
      <a class="nav-link" href="{{ url_for('list.unfinished') }}">Unfinished</a>
    </div>
  </div>
</nav>

<div class="container">
  {% block body %}{% endblock %}
</div>
</body>
</html>

templates/list_detail.html
{% extends "list_base.html" %}
{% block title %}Add{% endblock %}

{% block head %}
<script src="{{ url_for('static',filename="JQuery/details.js") }}"></script>
<script src="{{ url_for('static',filename="JS/detail.js") }}"></script>
<script src="{{ url_for('static',filename="assets/jquery.min.js") }}"></script>
<script src="{{ url_for('static',filename="assets/moment.min.js")}}"></script>
  <script src="{{ url_for('static',filename="assets/bootstrap.min.js")}}"></script>
<script src="{{ url_for('static',filename="assets/bootstrap-datetimepicker.min.js")}}"></script>
      <link rel="stylesheet" href="{{ url_for('static',filename="bootstrap/bootstrap.4.6.min.css") }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='css/user.css') }}">


{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-3"></div>
        <div  class="col-8" id="todo_detail">
            <h3 class="todo_title">{{ todo.title }}</h3>
            <p class="todo_info">
                <span>Create time: {{ todo.create_time }}</span>
                <span>Category: {{ todo.category }}</span>
            </p>
            <hr>
            <p class="todo_contents">Contents: {{ todo.content }}</p>
            <p class="todo_completion">Completed status: {{ todo.completion }} </p>
            <form  id="status" method="POST" action="{{ url_for('list.detail',todo_id=todo.id) }}">
                <button type="submit" id="completed" class="btn btn-primary">Change Status</button>
            </form>
        </div>
    </div>
{#    <div class="row">#}
{#        <div class="col-3"></div>#}
{#        <div class="col-8" id="change_status">#}
{#            <h3>Set new status for this issue</h3>#}
{#            <a href="{{ url_for('list.home') }}">#}
{#            <button type="button" method="POST" action="{{ url_for('list.home') }}" class="btn btn-outline-warning" id="completed">Completed</button>#}
{#            </a>#}
{#            <a href="{{ url_for('list.home') }}">#}
{#            <button type="button" class="btn btn-outline-info" id="uncompleted">Uncompleted</button>#}
{#            </a>#}
{#        </div>#}
{#    </div>#}

{% endblock %}

templates/list_finished.html
{% extends "list_base.html" %}
{% block title %}List_Finished{% endblock %}

{% block head %}
<script src="{{ url_for('static',filename="assets/jquery.min.js") }}"></script>
<script src="{{ url_for('static',filename="assets/moment.min.js")}}"></script>
<script src="{{ url_for('static',filename="assets/bootstrap.min.js")}}"></script>
<script src="{{ url_for('static',filename="assets/bootstrap-datetimepicker.min.js")}}"></script>
<link rel="stylesheet" href="{{ url_for('static',filename="bootstrap/bootstrap.4.6.min.css") }}">

{% endblock %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-3">the left side</div>
    <div class="col-6">
      <br><br>
      <div class="table-responsive">
        <table  class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Number</th>
              <th scope="col">Heading</th>
              <th scope="col">Status</th>
              <th scope="col">Deadline</th>
            </tr>
          </thead>

          <tbody>
            {% for todo in todos %}
              <tr>
                  <th scope="row"><a href="{{ url_for('list.detail',todo_id=todo.id) }}">{{ todo.id }}</a></th>
                <td>{{ todo.title }}</td>
                <td>{{ todo.completion }}</td>
                <td>Deadline</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-3">the right side</div>
  </div>
</div>
{% endblock %}

templates/list_home.html
{% extends "list_base.html" %}
{% block title %}List_Home{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename="bootstrap/bootstrap.4.6.min.css") }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='css/user.css') }}">
{% endblock %}

{% block body %}
{#  <div class="row">#}
{#    <div class="col"></div>#}
{#    <div class="col-8">#}
{#      <ul class="question-ul">#}
{#        {% for todo in todos %}#}
{#        <li>#}
{#          <div class="side-question">#}
{#            <!--头像-->#}
{#            <img class="side-question-avatar" src="{{ url_for('static',filename='images/1.jpg') }}" alt="">#}
{#          </div>#}
{##}
{#          <div class="question-main">#}
{#            <p class="question-title"><a href="#">{{ todo.title }}</a></p>#}
{#            <p class="question-content">{{ todo.content }}</p>#}
{#            <p class="question-detail">#}
{#              <span class="question-author">{{ todo.user.username }}</span>#}
{#              <span class="question-time">{{ todo.create_time }}</span>#}
{#            </p>#}
{#          </div>#}
{#        </li>#}
{#          <br><br>#}
{#        {% endfor %}#}
{#      </ul>#}
{#    </div>#}
{#    <div class="col"></div>#}
{#  </div>#}
<div class="container">
  <div class="row">
    <div class="col-3">the left side</div>
    <div class="col-6">
      <br><br>
      <div class="table-responsive">
        <table  class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Number</th>
              <th scope="col">Heading</th>
              <th scope="col">Status</th>
              <th scope="col">Deadline</th>
            </tr>
          </thead>

          <tbody>
            {% for todo in todos %}
              <tr>
                  <th scope="row"><a href="{{ url_for('list.detail',todo_id=todo.id) }}">{{ todo.id }}</a></th>
                <td>{{ todo.title }}</td>
                <td>{{ todo.completion }}</td>
                <td>Deadline</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-3">the right side</div>
  </div>
</div>
{% endblock %}

templates/list_unfinished.html
{% extends "list_base.html" %}
{% block title %}List_Unfinished{% endblock %}

{% block head %}
<script src="{{ url_for('static',filename="assets/jquery.min.js") }}"></script>
<script src="{{ url_for('static',filename="assets/moment.min.js")}}"></script>
<script src="{{ url_for('static',filename="assets/bootstrap.min.js")}}"></script>
<script src="{{ url_for('static',filename="assets/bootstrap-datetimepicker.min.js")}}"></script>
<link rel="stylesheet" href="{{ url_for('static',filename="bootstrap/bootstrap.4.6.min.css") }}">

{% endblock %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-3">the left side</div>
    <div class="col-6">
      <br><br>
      <div class="table-responsive">
        <table  class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Number</th>
              <th scope="col">Heading</th>
              <th scope="col">Status</th>
              <th scope="col">Deadline</th>
            </tr>
          </thead>

          <tbody>
            {% for todo in todos %}
              <tr>
                  <th scope="row"><a href="{{ url_for('list.detail',todo_id=todo.id) }}">{{ todo.id }}</a></th>
                <td>{{ todo.title }}</td>
                <td>{{ todo.completion }}</td>
                <td>Deadline</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="col-3">the right side</div>
  </div>
</div>
{% endblock %}

templates/user_login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Login</title>
{#  add the style link#}
  <link rel="stylesheet" href="{{ url_for('static',filename="bootstrap/bootstrap.4.6.min.css") }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='css/user.css') }}">
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-5">col-5(welcome slogan)</div>
    <div class="col-7" >
      <div class="regist_invitation">
        <h1>Do not have an account?</h1>
        <h1>Registrate now!</h1>
        <br>
{#        jump to the registration page if get this button#}
        <a href="{{ url_for('user.regist') }}">
          <button type="submit" class="btn btn-primary" >Go Registrate</button>
        </a>
      </div>
      <hr>
{#      connect login form to the login function and set the method as post#}
      <form id="login" action="{{ url_for("user.login") }}" method="POST">
        <div class="form-group">
          <label for="exampleInputEmail1">Enter Username</label>
{#            name this blocket as username#}
          <input name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
{#            name this blocket as password#}
          <input name="password" type="password" class="form-control" id="exampleInputPassword1">
        </div>
        <div class="form-group form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Remember me for 30 days</label>
        </div>

{#        if login doesn't success, then, show the error flashed message#}
        <div class="form-group">
        {% for message in get_flashed_messages() %}
          <div class="form-group">
            <div class="text-danger">{{ message }}</div>
          </div>
        {% endfor %}
        </div>
{#        redirect to the list_home page if login successfully#}
        <a href="{{ url_for('list.home') }}">
          <button type="submit" class="btn btn-primary" >Login</button>
        </a>
      </form>
    </div>
  </div>
</div>
</body>
</html>

templates/user_regist.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Registration</title>


  <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <script src="{{ url_for('static',filename="JS/regist.js") }}"></script>
  <link rel="stylesheet" href="{{ url_for('static',filename="bootstrap/bootstrap.4.6.min.css") }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='css/user.css') }}">

</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-5">col-5(welcome slogan)</div>
    <div class="col-7" >
      <form id="Registration" method="POST" action="{{ url_for('user.regist') }}">
        <div class="form-group">
          <label for="exampleFormControlInput1">Email address</label>
          <input type="email" name="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">Verification code</label>
          <div class="input-group">
            <input type="text"  class="form-control" name="catch">
            <div class="input-group-append">
{#                        获取验证码按钮，出发鼠标点击事件，见regist.js#}
              <button class="btn btn-outline-secondary" type="button" id="get_code">Get code</button>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label for="exampleInputPassword1">Set username</label>
          <input type="text"  class="form-control" name="username">
        </div>

        <div class="form-group">
          <label for="exampleInputPassword1">Set Password</label>
          <input type="password" name="password" class="form-control" id="exampleInputPassword1">
        </div>

        <div class="form-group">
          <label for="exampleInputPassword1">Confirm password</label>
          <input type="password"  class="form-control" name="password_confirm">
        </div>

        <div class="form-group">
          {% for message in get_flashed_messages() %}
            <div class="form-group">
              <div class="text-danger">{{ message }}</div>
            </div>
          {% endfor %}
        </div>

        <button type="submit" class="btn btn-primary">Registrate</button>
      </form>
    </div>
  </div>
</div>
</body>
</html>